
package com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AirportServiceService", targetNamespace = "http://ws.com/", wsdlLocation = "http://localhost:8888/ws/server?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class AirportServiceService
    extends Service
{

    private final static URL MUSICSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MUSICSERVICESERVICE_EXCEPTION;
    private final static QName MUSICSERVICESERVICE_QNAME = new QName("http://ws.com/", "AirportServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MUSICSERVICESERVICE_WSDL_LOCATION = url;
        MUSICSERVICESERVICE_EXCEPTION = e;
    }

    public AirportServiceService() {
        super(__getWsdlLocation(), MUSICSERVICESERVICE_QNAME);
    }

    public AirportServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MUSICSERVICESERVICE_QNAME, features);
    }

    public AirportServiceService(URL wsdlLocation) {
        super(wsdlLocation, MUSICSERVICESERVICE_QNAME);
    }

    public AirportServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MUSICSERVICESERVICE_QNAME, features);
    }

    public AirportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AirportService
     */
    @WebEndpoint(name = "AirportServicePort")
    public AirportService getAirportServicePort() {
        return super.getPort(new QName("http://ws.com/", "AirportServicePort"), AirportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirportService
     */
    @WebEndpoint(name = "AirportServicePort")
    public AirportService getAirportServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.com/", "AirportServicePort"), AirportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MUSICSERVICESERVICE_EXCEPTION!= null) {
            throw MUSICSERVICESERVICE_EXCEPTION;
        }
        return MUSICSERVICESERVICE_WSDL_LOCATION;
    }

}
